baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Jason Locklin"
theme = "hugo-base-theme"

[params]
  description = "Research Scientist, Science and Tech Enthusiest."
  location = "Kitchener, Ontario."
  mainIcon = "/img/jason.png"

[[params.social]]
    title = "t"
    url = "https://twitter.com/jalockli"
[[params.social]]
    title = "g"
    url = "https://github.com/JasonLocklin"
[[params.social]]
    title = "l"
    url = "https://ca.linkedin.com/in/locklinjason"
